def header():
    print('_______________________________________________________________________________')
    print()
    print('                 /////////       //////////     /////////')
    print('                 //              //     //      //')
    print('                 //              ////////       //////')
    print('                 //   ////       //                 /////')
    print('                 //     //       //                    //')
    print('                 /////////       //             /////////') 
    print()
    print('                 C       U       P       I       D       O')
    print()
    print('>>>------Calcularemos la ruta mas rápida y segura para ver a tu pareja------->')
    print('_______________________________________________________________________________')

def menu():
    print('')
    print('>>>------MENÚ PRINCIPAL------->')
    print('Ingrese una de las siguiente opciones\n')
    print('[1] Iniciar GPS\n')
    print('[2] Sobre nosotros\n')
    print('[3] Contáctanos\n')
    print('[0] Cerrar GPS Cupido\n')


def gps():
    print('')
    print('>>>------INICIAR GPS------->')
    print('Ingresa uno de las siguientes destinos:\n')
    print('[1] Discoteca The Darkness: Carrera 14 con Calle 50\n')
    print('[2] Bar La Pasión: Calle 54 con Carrera 11\n')
    print('[3] Cervecería Mi Rolita: Calle 50 con Carrera 12\n')
    print('[0] Volver a menú principal\n')

def aboutUs():
    print('')
    print('>>>------SOBRE NOSOTROS------->\n')
    print('GPS Cupido es una compañia en busca de unir amores prohibidos')
    print('y evitar desgracias como las que vivieron Romeo y Julieta')
    print('proporcionando rutas rápidas y seguras para que tu y tu pareja')
    print('lleguen a sus destinos deseados sin ser vistos por sus padres.\n')
    print('[0] Regresar a menú principal\n')

def contact():
    print('')
    print('>>>------CONTACTANOS------->\n')
    name = input("Ingrese su nombre y apellido: \n")
    email = input("\nIngrese su correo electrónico: \n")
    content = input("\n¿Cuál es el motivo de su mensaje?: \n")
    print('\n\n¿Deseas enviar este mensaje?\n')
    print('De:', name, ': <', email, '>')
    print('Para: GPS Cupido\n')
    print(content)
    print('\n[1] Enviar\n')

def credits():
    print('\nProyecto 1 - Modelación de Sistemas en Redes')
    print('Profesor:')
    print('     >-Rafael Matienzo->')
    print('\nIntegrantes:')
    print('     >-Oriana González->')
    print('     >-Guillermo Sosa->')
    print('     >-Luis Stanislao->')
    print('\nGPS Cupido finalizado\n')

def routes():
    print('_______________________________________________________________________________')
    print()
    print('      ////////     ///     ///    ////////      //////       /////////')
    print('      //    //     ///     ///      ///        ///////       //')
    print('      ///////      ///     ///      ///       ///   ///       ////')
    print('      //   ///     ///     ///      ///      ///////////         ////')
    print('      //    ///    ///     ///      ///     ///       ///           //')
    print('      //     ///    /////////       ///    ///         ///   /////////')
    print('_______________________________________________________________________________')
    print()

def aboutHeader():
    print('_______________________________________________________________________________')
    print()
    print('          //////       //////////      /////////    ///     ///   //////////')
    print('         ////////      ///     ///    ///     ///   ///     ///      ///')
    print('        ///   ///      ///////////    ///     ///   ///     ///      ///')
    print('       ///////////     ///     ///    ///     ///   ///     ///      ///')
    print('      ///       ///    ///     ///    ///     ///   ///     ///      ///')
    print('     ///         ///   /////////       /////////     /////////       ///')
    print('_______________________________________________________________________________')
    print()

def contactHeader():
    print('_______________________________________________________________________________')
    print()
    print(' /////////    /////////    ///    ///       //////      //////////  //////////')
    print(' //    //    ///     ///   ////    //      ////////     //     //      ///')
    print(' //          ///     ///   // //   //     ///   ///     //             ///')
    print(' //          ///     ///   //   // //    ///////////    //             ///')
    print(' //     //   ///     ///   //    ////   ///       ///   //     //      ///')
    print(' ////////     /////////    //     ///  ///         ///  /////////      ///')
    print('_______________________________________________________________________________')
    print()